
export const ERROR_MSG = {
	NAME_INVALID: 'NAME_INVALID',
	PASSWORD_INVALID: 'PASSWORD_INVALID',
	PHONE_INVALID: 'PHONE_INVALID',
	PHONE_DUPLICATE: 'PHONE_DUPLICATE',
	PHONE_NOT_FOUND: 'PHONE_NOT_FOUND',
	USER_NOT_FOUND: 'USER_NOT_FOUND',
	PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
	MA_CUA_HANG_INVALID: 'MA_CUA_HANG_INVALID',

	// TOKEN
	ACCESS_TOKEN_INVALID: 'ACCESS_TOKEN_INVALID',
	REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
	REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
	MAX_ATTEMPTS_EXCEEDED: 'MAX_ATTEMPTS_EXCEEDED',

	// HTTP CODE
	SOMETHING_WENT_WRONG: 'SOMETHING_WENT_WRONG',
	UNAUTHORIZED: 'UNAUTHORIZED',
	TOKEN_INVALID: 'TOKEN_INVALID',
	FORBIDDEN: 'FORBIDDEN',
	BAD_REQUEST: 'BAD_REQUEST',
	CONFLICT: 'CONFLICT',
};

export const SUCCESS_MSG = {
	SUCCESSFUL: 'SUCCESSFUL',
	LOGIN: 'LOGIN_SUCCESSFUL',
	REGISTER: 'REGISTER_SUCCESSFUL',
	LOGOUT: 'LOGOUT_SUCCESSFUL',
	ACCESS_TOKEN: 'ACCESS_TOKEN_GENERATED_SUCCESSFUL',
};
